library(shiny)
library(shinythemes)
library(shinyBS)
library(shinyFeedback)

ui <- fluidPage(
  title="Measurement error bias in linear regression", theme=shinytheme("lumen"),
  titlePanel(h1("Measurement error bias in linear regression", align="center")),
  fluidRow(
    plotOutput(outputId="scatterPlot", height="700px"),
    shinyFeedback::useShinyFeedback()
  ),
  
  fluidRow(
    column(2,
           h3("Data generation"),
           numericInput("n",
                        label="Number of observations:",
                        value=100,
                        step=10,
                        min=1,
                        max=100000,
                        width="80%"),
           numericInput("sd_res",
                        label="Residual variation (sd):",
                        value=1,
                        step=0.1,
                        min=0,
                        width="80%"),
           numericInput("beta0",
                        label="Intercept:",
                        value=0,
                        step=0.1,
                        width="80%"),
           numericInput("beta1",
                        label="Slope:",
                        value=1,
                        step=0.1,
                        width="80%"),
           div(style="padding: 10px 0px 0px 0px;", 
               actionButton("generate", 
                            label="Generate new data",
                            width="80%")
           ),
           offset=1
    ),
    column(2,
           h3("Preferences"),
           div(style="padding: 15px 0px 0px 0px;", 
               radioButtons("toggle_points", 
                            label="Observations:",
                            choices=c("Show"=TRUE, "Hide"=FALSE),
                            selected=TRUE,
                            inline=TRUE)
           ),
           div(style="padding: 0px 0px 0px 0px;", 
               radioButtons("toggle_error", 
                            label="Measurement error:",
                            choices=c("On"=TRUE, "Off"=FALSE),
                            selected=FALSE,
                            inline=TRUE)
           ),
           div(style="padding: 0px 0px 0px 0px;", 
               radioButtons("toggle_connect", 
                            label="Connect observations:",
                            choices=c("On"=TRUE, "Off"=FALSE),
                            selected=FALSE,
                            inline=TRUE)
           ),
           sliderInput("transparency", 
                       label="Transparency (observations):",
                       min=0,
                       max=1,
                       value=1,
                       step=0.05,
                       width="80%"),
           sliderInput("transparency_seg",
                       label="Transparency (segments):",
                       min=0,
                       max=1,
                       value=0.1,
                       step=0.05,
                       width="80%")
    ),
    column(2,
           h3("Measurement error in X"),
           numericInput("error_mean_x",
                        label="Measurement error (mean):",
                        value=0,
                        step=0.1,
                        width="80%"),
           numericInput("error_sd_x",
                        label="Measurement error (sd):",
                        value=0,
                        step=0.1,
                        width="80%"),
           sliderInput("yrange",
                       label="Measurement error applied to Y-values:",
                       min=-10,
                       max=10,
                       value=c(-10,10),
                       width="80%"),
           div(style="padding: 0px 0px 15px 0px;", 
               actionButton("reset_error_x",
                            label="Reset measurement error in X",
                            width="80%")
           ),
    ),
    column(2,
           h3("Measurement error in Y"),
           numericInput("error_mean_y",
                        label="Measurement error (mean):",
                        value=0,
                        step=0.1,
                        width="80%"),
           numericInput("error_sd_y",
                        label="Measurement error (sd):",
                        value=0,
                        step=0.1,
                        width="80%"),
           sliderInput("xrange",
                       label="Measurement error applied to X-values:",
                       min=-10,
                       max=10,
                       value=c(-10,10),
                       width="80%"),
           actionButton("reset_error_y",
                        label="Reset measurement error in Y",
                        width="80%"),
    ),
    column(2,
           h3("Results"),
           h4("Estimates (without error)"),
           tableOutput("estimates_all"),
           h4("Estimates (with error)"),
           tableOutput("estimates_sel"),
    )
  ),
  
  bsTooltip(id="error_mean_x", title="Systematic error in X", placement="right", trigger="hover"),
  bsTooltip(id="error_mean_y", title="Systematic error in Y", placement="right", trigger="hover"),
  bsTooltip(id="error_sd_x", title="Random error in X", placement="right", trigger="hover"),
  bsTooltip(id="error_sd_y", title="Random error in Y", placement="right", trigger="hover"),
  bsTooltip(id="yrange", title="Apply measurement error to these Y-values", placement="right", trigger="hover"),
  bsTooltip(id="xrange", title="Apply measurement error to these X-values", placement="right", trigger="hover"),
  
)